version: "3.1"

networks:
  single-network:
services:
  # ################ Runtime  ##############
  runtime:
    image: tearust/runtime:dev
    container_name: "runtime"
    networks:
      - single-network
    volumes:
      - ../local:/wasm-local
    environment:
      RUST_BACKTRACE: full
      CLIENT_HOST: parent-instance-client
      MALLOC_CONF: prof:true
      RUST_LOG: INFO,wasmer=WARN,regalloc2=WARN

  parent-instance-client:
    image: tearust/parent-instance-client:dev-cli
    container_name: "parent-instance-client"
    networks:
      - single-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
    volumes:
      - .log:/log
      - .tokenstate:/tokenstate
      - .libp2p:/libp2p
      - .layer1:/layer1
      - ../data:/tearust/data
    environment:
      ENCLAVE_HOST: runtime
      SELF_HOST: parent-instance-client
      LOG_FILE: /log/output.log
      GENESIS_CONFIG_PATH: /tearust/data/genesis.json
      LAYER1_WS_PROVIDER_URL: ws://host.docker.internal:8545/
      LAYER1_KEY_PATH: /layer1/key
      LASTEST_TOPUP_HEIGHT: 1
      TEA_ID: "0x0000000000000000000000000000000000000000000000000000000000000000"
      MACHINE_OWNER: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
      LIBP2P_NODE_KEY_PATH: /libp2p/key
      LIBP2P_SUPPORTED_PROTOCOLS: local0.1
      APPLY_VALIDATOR: "true"
      STATE_MAGIC_NUMBER: 100
      PERSIST_PATH: /tokenstate/persist
      RUST_BACKTRACE: full
      MALLOC_CONF: prof:true
      LOCAL_WASM_FOLDER: /wasm-local

      WAIT_HOSTS: runtime:5005
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
    entrypoint: /bin/bash
    stdin_open: true # docker run -i
    tty: true # docker run -t
